name: Ingestion & QA

on:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: aminata
          POSTGRES_PASSWORD: aminata
          POSTGRES_DB: dwh_don_sang
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U aminata"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export PG env
        run: |
          echo "PG_HOST=localhost" >> $GITHUB_ENV
          echo "PG_PORT=5432" >> $GITHUB_ENV
          echo "PG_USER=aminata" >> $GITHUB_ENV
          echo "PG_PASSWORD=aminata" >> $GITHUB_ENV
          echo "PG_DB=dwh_don_sang" >> $GITHUB_ENV

      - name: Ingestion -> Data Lake (Parquet)
        run: python -m src.ingestion.ingest_to_datalake

      - name: Load RAW -> PostgreSQL
        run: python -m src.ingestion.load_to_postgres

      - name: Build CLEAN table
        run: python -m src.transformation.clean_postgres_data

      - name: Run Quality Checks
        run: python -m src.qa.run_quality_checks
      - name: Setup GCP credentials
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp_key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp_key.json" >> $GITHUB_ENV
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "BQ_DATASET_ID=${{ secrets.BQ_DATASET_ID }}" >> $GITHUB_ENV

      - name: Load CLEAN -> BigQuery
        run: python -m src.ingestion.load_clean_to_bigquery